export {
  canAccessRoute,
  canAccessRouteWithAllowed,
  canAccessNavTab,
  canWriteUsers,
  canManageAccounts,
  canManageProjects,
  isProjectScopedRole,
  rolesRequiringProjects,
  normalizePath,
  resolveAllowedRoutes,
  defaultAllowedRoutesForRole,
  CONFIGURABLE_ROUTES,
  type AppRole,
} from '@acv2/shared';
